"""initial schema

Revision ID: 4976fcd78bbc
Revises: 
Create Date: 2026-08-29 11:31:17.785139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4976fcd78bbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_type_active', 'companies', ['insurance_type', 'is_active'], unique=False)
    op.create_table('general_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gr_category', 'general_riders', ['category'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pm_category', 'product_master', ['category', 'sub_category'], unique=False)
    op.create_index('ix_pm_type_company', 'product_master', ['insurance_type', 'company_name'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_location_id'), 'users', ['location_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_location_id'), 'vehicles', ['location_id'], unique=False)
    op.create_table('field_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_members_location_id'), 'field_members', ['location_id'], unique=False)
    op.create_index('ix_fm_location_status', 'field_members', ['location_id', 'approval_status'], unique=False)
    op.create_index('ix_fm_requested_by', 'field_members', ['requested_by'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_term', sa.Integer(), nullable=True),
    sa.Column('premium_payment_mode', sa.String(length=10), nullable=True),
    sa.Column('ppt_term', sa.Integer(), nullable=True),
    sa.Column('number_of_lives', sa.Integer(), nullable=True),
    sa.Column('health_rider', sa.String(length=500), nullable=True),
    sa.Column('sum_assured', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sum_insured', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('premium_mode', sa.String(length=50), nullable=False),
    sa.Column('base_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rider_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_health_sickness', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_accident_disability', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_term_rider', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_other_pwb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_adb', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_atpd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_permanent_disability', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_critical_illness', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_waiver_of_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rider_terminal_illness', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('policy_status', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index(op.f('ix_policies_location_id'), 'policies', ['location_id'], unique=False)
    op.create_index(op.f('ix_policies_policy_status'), 'policies', ['policy_status'], unique=False)
    op.create_index('ix_policy_agent', 'policies', ['agent_name'], unique=False)
    op.create_index('ix_policy_company', 'policies', ['company'], unique=False)
    op.create_index('ix_policy_created', 'policies', ['created_at'], unique=False)
    op.create_index('ix_policy_dates', 'policies', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_policy_type_status', 'policies', ['insurance_type', 'policy_status'], unique=False)
    op.create_table('policy_covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=False),
    sa.Column('sum_insured', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cover_policy', 'policy_covers', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_covers_policy_id'), 'policy_covers', ['policy_id'], unique=False)
    op.create_table('policy_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('renewed_by', sa.Integer(), nullable=True),
    sa.Column('renewed_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_history_policy_id'), 'policy_history', ['policy_id'], unique=False)
    op.create_table('policy_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('sum_insured', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('excess_type', sa.String(length=20), nullable=True),
    sa.Column('excess_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('excess_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['general_riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_riders_policy_id'), 'policy_riders', ['policy_id'], unique=False)
    op.create_index('ix_pr_policy', 'policy_riders', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pr_policy', table_name='policy_riders')
    op.drop_index(op.f('ix_policy_riders_policy_id'), table_name='policy_riders')
    op.drop_table('policy_riders')
    op.drop_index(op.f('ix_policy_history_policy_id'), table_name='policy_history')
    op.drop_table('policy_history')
    op.drop_index(op.f('ix_policy_covers_policy_id'), table_name='policy_covers')
    op.drop_index('ix_cover_policy', table_name='policy_covers')
    op.drop_table('policy_covers')
    op.drop_index('ix_policy_type_status', table_name='policies')
    op.drop_index('ix_policy_dates', table_name='policies')
    op.drop_index('ix_policy_created', table_name='policies')
    op.drop_index('ix_policy_company', table_name='policies')
    op.drop_index('ix_policy_agent', table_name='policies')
    op.drop_index(op.f('ix_policies_policy_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_location_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_fm_requested_by', table_name='field_members')
    op.drop_index('ix_fm_location_status', table_name='field_members')
    op.drop_index(op.f('ix_field_members_location_id'), table_name='field_members')
    op.drop_table('field_members')
    op.drop_index(op.f('ix_vehicles_location_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_location_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_role_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_pm_type_company', table_name='product_master')
    op.drop_index('ix_pm_category', table_name='product_master')
    op.drop_table('product_master')
    op.drop_table('locations')
    op.drop_index('ix_gr_category', table_name='general_riders')
    op.drop_table('general_riders')
    op.drop_index('ix_company_type_active', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###